### ISSUE TITLE
Apple Pay

### ISSUE THREAD

**Issue by interpegasus** [marcolanaro/react-payment-request-api#2]
Hi, I would like to know if support for Apple Pay is implemented or can be added?

https://webkit.org/blog/8182/introducing-the-payment-request-api-for-apple-pay/

Thank you!

**Comment by marcolanaro** [comment]
Hi @interpegasus ,
I've added the support for [onmerchantvalidation](https://developer.apple.com/documentation/apple_pay_on_the_web/apple_pay_js_api/providing_merchant_validation) handler.

The examples folder now contains an advanced example using Apple Pay.
Please note that given I do not have a server implementation, in my example the merchant cannot be validated.

I'm going to close this issue given that version 3.1.0 now support Apple Pay.
Please let me know if you find any bug.
